import type {
  ArchUnit,
  CpuLayer,
  LatencyData,
  OptimizationGroup,
  PCComponent,
  PipelineStage,
  SoftwareLayer,
  SystemSnapshot,
  VoidtuneInfo,
} from '../types';

export function InfoPanel({
  component,
  onClose,
}: {
  component: PCComponent | null;
  onClose: () => void;
}) {
  if (!component) return null;
  return (
    <aside className="panel panel-right" aria-live="polite">
      <button className="panel-close" onClick={onClose} aria-label="Close information panel">
        ×
      </button>
      <h2>{component.name}</h2>
      <p className="panel-short">{component.short}</p>
      <p>{component.description}</p>
      {component.facts.length > 0 && (
        <>
          <h3>Worth knowing</h3>
          <ul>
            {component.facts.map((fact) => (
              <li key={fact}>{fact}</li>
            ))}
          </ul>
        </>
      )}
      {component.connects_to.length > 0 && (
        <>
          <h3>Connects to</h3>
          <p className="panel-tags">
            {component.connects_to.map((id) => (
              <span key={id} className="tag">
                {id.replace(/_/g, ' ')}
              </span>
            ))}
          </p>
        </>
      )}
    </aside>
  );
}

export function TextPanel({
  title,
  subtitle,
  body,
  note,
  onClose,
}: {
  title: string;
  subtitle?: string;
  body: string;
  note?: string;
  onClose: () => void;
}) {
  return (
    <aside className="panel panel-right" aria-live="polite">
      <button className="panel-close" onClick={onClose} aria-label="Close information panel">
        ×
      </button>
      <h2>{title}</h2>
      {subtitle && <p className="panel-short">{subtitle}</p>}
      <p>{body}</p>
      {note && <p className="panel-note">{note}</p>}
    </aside>
  );
}

export function Dashboard({ snapshot }: { snapshot: SystemSnapshot | null }) {
  if (!snapshot) return null;
  const bar = (value: number, max = 100) => `${Math.min(100, (value / max) * 100)}%`;
  return (
    <aside className="panel panel-left dashboard">
      <header className="dash-head">
        <h3>System activity</h3>
        {snapshot.simulated && <span className="sim-badge">SIMULATED</span>}
      </header>
      <p className="dash-note">
        Not your machine. These values are generated by the backend to drive the visualization.
      </p>

      <div className="metric">
        <span>CPU</span>
        <div className="meter">
          <i style={{ width: bar(snapshot.cpu_usage) }} />
        </div>
        <b>{snapshot.cpu_usage.toFixed(0)}%</b>
      </div>
      <div className="metric-sub">{snapshot.cpu_frequency_ghz.toFixed(2)} GHz</div>

      <div className="cores" aria-label="Per-core utilisation">
        {snapshot.cores.map((core, index) => (
          <div key={index} className="core" title={`Core ${index}: ${core.toFixed(0)}%`}>
            <i style={{ height: `${core}%` }} />
          </div>
        ))}
      </div>

      <div className="metric">
        <span>GPU</span>
        <div className="meter">
          <i style={{ width: bar(snapshot.gpu_usage) }} />
        </div>
        <b>{snapshot.gpu_usage.toFixed(0)}%</b>
      </div>
      <div className="metric">
        <span>RAM</span>
        <div className="meter">
          <i style={{ width: bar(snapshot.ram_used_gb, snapshot.ram_total_gb) }} />
        </div>
        <b>
          {snapshot.ram_used_gb.toFixed(1)}/{snapshot.ram_total_gb}G
        </b>
      </div>
      <div className="metric">
        <span>VRAM</span>
        <div className="meter">
          <i style={{ width: bar(snapshot.vram_used_gb, snapshot.vram_total_gb) }} />
        </div>
        <b>
          {snapshot.vram_used_gb.toFixed(1)}/{snapshot.vram_total_gb}G
        </b>
      </div>
      <div className="metric-sub">
        Disk R {snapshot.storage_read_mbs.toFixed(0)} / W {snapshot.storage_write_mbs.toFixed(0)} MB/s ·
        Net {snapshot.network_mbps.toFixed(0)} Mb/s
      </div>
    </aside>
  );
}

/** Measured cache latency from c/cpuinfo.c -- real data from the build machine. */
export function LatencyChart({ data }: { data: LatencyData | null }) {
  if (!data || data.latency.length === 0) return null;
  const max = Math.max(...data.latency.map((sample) => sample.latency_ns));
  return (
    <div className="latency">
      <h3>Measured memory latency</h3>
      <p className="panel-note">
        Real measurement, not a diagram: <code>c/cpuinfo.c</code> pointer-chases a shuffled cycle so each
        load depends on the last, then times it at increasing working-set sizes. The steps are this
        machine's cache levels.
      </p>
      <div className="latency-bars">
        {data.latency.map((sample) => (
          <div key={sample.working_set_kb} className="latency-row">
            <span className="latency-size">
              {sample.working_set_kb >= 1024
                ? `${sample.working_set_kb / 1024}M`
                : `${sample.working_set_kb}K`}
            </span>
            <div className="latency-track">
              <i style={{ width: `${(sample.latency_ns / max) * 100}%` }} />
            </div>
            <span className="latency-value">{sample.latency_ns.toFixed(1)} ns</span>
          </div>
        ))}
      </div>
      <p className="panel-note">
        Cache layout reported by the kernel:{' '}
        {data.caches.map((cache) => `L${cache.level} ${cache.type[0]} ${cache.size_kb}KB`).join(' · ')}
      </p>
    </div>
  );
}

export function VoidtunePanel({
  info,
  groups,
  selectedCategory,
  onSelectCategory,
}: {
  info: VoidtuneInfo | null;
  groups: OptimizationGroup[];
  selectedCategory: string | null;
  onSelectCategory: (category: string | null) => void;
}) {
  if (!info) return null;
  const selected = groups.find((group) => group.category === selectedCategory) ?? null;
  return (
    <aside className="panel panel-right wide">
      <h2>{info.name}</h2>
      <p className="panel-short">
        v{info.version} · {info.platform} · {info.license}
      </p>
      <p>{info.summary}</p>

      <h3>What it does</h3>
      <ul>
        {info.what_it_does.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
      <h3>What it does not do</h3>
      <ul className="negative">
        {info.what_it_does_not_do.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>

      <h3>
        Tweak catalog <span className="count">{info.total_tweaks} total</span>
      </h3>
      <p className="panel-note">
        Parsed directly from <code>TweakCatalog.cs</code> in the VOIDTUNE repo. Selecting a category
        highlights the component it affects in the scene.
      </p>
      <div className="chips">
        {groups.map((group) => (
          <button
            key={group.category}
            className={`chip ${selectedCategory === group.category ? 'on' : ''}`}
            onClick={() => onSelectCategory(selectedCategory === group.category ? null : group.category)}
          >
            {group.category} <b>{group.count}</b>
          </button>
        ))}
      </div>

      {selected && (
        <div className="tweak-list">
          <h3>
            {selected.category}
            {selected.component_id && <span className="count">affects {selected.component_id}</span>}
          </h3>
          {selected.tweaks.slice(0, 40).map((tweak) => (
            <div key={tweak.id} className="tweak">
              <div className="tweak-head">
                <b>{tweak.name}</b>
                <span className={`tier ${tweak.tier.toLowerCase()}`}>{tweak.tier.toUpperCase()}</span>
                {tweak.needs_reboot && <span className="tier reboot">REBOOT</span>}
              </div>
              <p>{tweak.description}</p>
            </div>
          ))}
          {selected.tweaks.length > 40 && (
            <p className="panel-note">+{selected.tweaks.length - 40} more in this category.</p>
          )}
        </div>
      )}
    </aside>
  );
}

/** Text-only rendering of every scene's content, shown when WebGL is
 * unavailable. The educational content must survive without 3D. */
export function TextFallback({
  components,
  cpuLayers,
  pipeline,
  units,
  software,
  voidtune,
  groups,
}: {
  components: PCComponent[];
  cpuLayers: CpuLayer[];
  pipeline: PipelineStage[];
  units: ArchUnit[];
  software: SoftwareLayer[];
  voidtune: VoidtuneInfo | null;
  groups: OptimizationGroup[];
}) {
  return (
    <div className="fallback">
      <h1>VOIDTUNE — PC architecture</h1>
      <p className="panel-note">
        WebGL is unavailable in this browser, so the 3D experience cannot run. The full content is
        below as text.
      </p>

      <h2>Components</h2>
      {components.map((component) => (
        <section key={component.id}>
          <h3>{component.name}</h3>
          <p>{component.description}</p>
        </section>
      ))}

      <h2>Inside the CPU</h2>
      {cpuLayers.map((layer) => (
        <section key={layer.id}>
          <h3>
            {layer.name} <small>{layer.scale}</small>
          </h3>
          <p>{layer.description}</p>
        </section>
      ))}

      <h2>Pipeline</h2>
      {pipeline.map((stage) => (
        <section key={stage.id}>
          <h3>{stage.name}</h3>
          <p>{stage.description}</p>
        </section>
      ))}

      <h2>Functional units</h2>
      {units.map((unit) => (
        <section key={unit.id}>
          <h3>{unit.name}</h3>
          <p>{unit.description}</p>
        </section>
      ))}

      <h2>Software to hardware</h2>
      {software.map((layer) => (
        <section key={layer.id}>
          <h3>{layer.name}</h3>
          <p>{layer.description}</p>
        </section>
      ))}

      {voidtune && (
        <>
          <h2>{voidtune.name}</h2>
          <p>{voidtune.summary}</p>
          <h3>What it does</h3>
          <ul>
            {voidtune.what_it_does.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
          <h3>What it does not do</h3>
          <ul>
            {voidtune.what_it_does_not_do.map((item) => (
              <li key={item}>{item}</li>
            ))}
          </ul>
          <h3>Catalog ({voidtune.total_tweaks} tweaks)</h3>
          <ul>
            {groups.map((group) => (
              <li key={group.category}>
                {group.category}: {group.count}
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  );
}
